### PR TITLE
Remove fields from outputs

### PR DESCRIPTION
**Pull request by radu-matei**
https://github.com/deislabs/cnab-spec/issues/234 removes `fields` from outputs, and this PR is issued at the same time with the spec change.

Since #82 adds runtime support for outputs, there is also the option to directly roll this change there - I don't have a strong preference.

### CODE REVIEW

**Comment by jeremyrickard** [comment]
Let's do #82 first, then circle back to this. that one has had enough churn and i'd prefer incremental changes.

**Comment by silvin-lubecki** [comment]
@radu-matei can you rebase this PR? 🦁

**Comment by radu-matei** [comment]
@silvin-lubecki - I'd rather wait for #82, then do a rebase.

**Comment by silvin-lubecki** [comment]
Still LGTM 👍

**Pull request merged**
